#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
fpath=(/usr/local/share/zsh-completions $fpath)

export PATH="/usr/local/opt/python/libexec/bin:$PATH"
#export PATH="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:$PATH"

# vim mode
bindkey -v
export KEYTIMEOUT=1

# disable autocorrect from utility module
unsetopt CORRECT

# vim default editor
export VISUAL='/usr/local/bin/vim'
export EDITOR='/usr/local/bin/vim'

alias rabc='rabbitmqctl'

# aliases
alias rz="source ~/.zshrc"
alias rzp="source ~/.zpreztorc"
alias ez="$EDITOR ~/.zshrc"
alias ezp="$EDITOR ~/.zpreztorc"
alias et="$EDITOR ~/.tmux.conf"
alias ev="$EDITOR ~/.vimrc"
#alias vim='nvim'

# solarize light
export FZF_DEFAULT_OPTS='
--color fg:240,bg:230,hl:33,fg+:241,bg+:221,hl+:33
--color info:33,prompt:33,pointer:166,marker:166,spinner:33
'
# solarized dark
export FZF_DEFAULT_OPTS='
--color dark,hl:33,hl+:37,fg+:235,bg+:136,fg+:254
--color info:254,prompt:37,spinner:108,pointer:235,marker:235
'

# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
export FZF_CTRL_T_COMMAND='rg --files --hidden --follow --glob "!.git/*"'

alias rg="rg -i"

# git aliases
alias gst='git status'
alias gaa='git add --all'
alias gd='git diff'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcom='git checkout master'
alias gcod='git checkout develop'
alias gp='git push'
alias gpu='git push -u'
alias gptu='git push upstream'
alias gptuf='git push upstream -f'
alias gf='git pull --rebase'
alias gca='gc --amend'
alias gb='git branch --list'
alias grm='git rebase master'
alias grd='git rebase develop'
alias gro='git rebase --onto'
alias gfp="git fetch -p"
alias gacapf="gaa && gca --no-edit && gpf"
alias gfu="git fetch upstream && git checkout master && git merge upstream/master && git push"

# tmux aliases
alias tnew="tmux new -s"
alias ta="tmux a -t"
alias tl="tmux ls"
alias tk="tmux kill-session -t"
alias rt="tmux source-file ~/.tmux.conf"

# solvvy specific aliases
alias tun="/Users/paymahn/solvvy/misc-scripts/src/ruby/tunnel.rb"

# utility aliases
alias grepp="grep -iIrnp"

# virtualenv
alias vac="source venv/bin/activate || source .venv/bin/activate"
alias dac="deactivate"

# docker
alias d="docker"
alias dc="docker-compose"
alias dzk="docker-compose kill"

# this is a doozie. The inner command gets the container id of the last run
# container
# The rest of this connects to a container and starts bash
alias clc="docker exec -t -i $(docker ps -aq --last 1) /bin/bash"

# kubernetes
alias k="kubectl"
alias mk="minikube"
alias kgp="k get pods"
alias kgd="k get deployments"
alias kl="k logs"
alias klf="kl -f"
alias kdp="k describe pod"
alias kgsv="k get svc"
alias kdsv="k describe svc"
alias kccc='k config current-context'
alias kcuc='k config use-context'
alias up="kubectl config use-context scheduler-prod"
alias ud="kubectl config use-context scheduler-dev"
alias um="kubectl config use-context mycro"
alias ul="kubectl config use-context mk-scheduler"
alias umk="kubectl config use-context minikube"
alias dd="ud && k apply -f kubernetes-dev.yml"
alias dp="up && k apply -f kubernetes-prod.yml"
alias stm="gcloud auth login && gcloud config set project mycrocoin && gcloud container clusters get-credentials main-clone-1 --zone us-west1-b --project mycrocoin && kubectl config use-context mycro "
alias stsd="gcloud auth login && gcloud config set project solvvy-dev && gcloud container clusters get-credentials kube1 && kubectl config use-context scheduler-dev"
alias stsp="gcloud auth login && gcloud config set project solvvy-production && gcloud container clusters get-credentials main-prod && kubectl config use-context scheduler-prod"

alias pm='export CURDIR=`basename $PWD` && gd --name-only HEAD~1 | rg $CURDIR |  rg ".*\.py$" | sed -e "s/$CURDIR\///g"  | xargs poetry run mypy && unset CURDIR'
alias pp='export CURDIR=`basename $PWD` && gd --name-only HEAD~1 | rg $CURDIR | rg ".*\.py$" | sed -e "s/$CURDIR\///g"  | xargs poetry run pylint && unset CURDIR'
alias pt='poetry run pytest'

# envsubst isn't linked when installed with brew
alias envsubst="/usr/local/opt/gettext/bin/envsubst"

alias yaml2js="python3 -c 'import sys, yaml, json; [json.dump(y, sys.stdout, indent=4) for y in yaml.load_all(sys.stdin)]'"

function light() {
  sed -i '' "s/background=dark/background=light/g" ~/.vimrc
  sed -i '' "s/solarized '256'/solarized 'light'/g" ~/.tmux.conf
  tmux source-file ~/.tmux.conf
}
function dark() {
  sed -i '' "s/background=light/background=dark/g" ~/.vimrc
  sed -i '' "s/solarized 'light'/solarized '256'/g" ~/.tmux.conf
  tmux source-file ~/.tmux.conf
}


#bindkey -e
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export AIRFLOW_HOME="/usr/local/airflow"
eval "$(pyenv init -)"
export PATH="/usr/local/opt/postgresql@9.6/bin:$PATH"

export NPM_TOKEN="b4bb2747-0058-4a08-9ba7-2d4fe22fead4"

# android
export ANDROID_HOME=/Users/paymahn/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
source /Users/$USER/Library/Python/3.7/bin/virtualenvwrapper.sh
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3.7
export VIRTUALENVWRAPPER_VIRTUALENV=/Users/$USER/Library/Python/3.7/bin/virtualenv
export PATH="/usr/local/opt/protobuf@3.7/bin:$PATH"
export PATH="/usr/local/opt/node@10/bin:$PATH"

function revert-expand-or-complete {
  zle expand-or-complete
}

zle -N expand-or-complete-with-indicator revert-expand-or-complete

